#index:
#    path: /
#    controller: App\Controller\DefaultController::index
terrain_statistics:
    path: /terrain/type/stats
    controller: App\Controller\ServiceTerrainController::terrainTypeStats